### ISSUE TITLE
Invalid CSS after "...typography-h1()": expected "}"

### ISSUE THREAD

**Issue by theasteve** [CityOfNewYork/ACCESS-NYC-PATTERNS#1]
Loading the `ACCESS_NYC_PATTERNS` library into rails application break on `@import 'components/header/header';` The error states `Invalid CSS after "...typography-h1()": expected "}", was "margin-bottom: ..."` 
<img width="1044" alt="screen shot 2018-08-14 at 12 00 17 pm" src="https://user-images.githubusercontent.com/14843767/44103232-ad75fa44-9fb9-11e8-8a60-7b5461c7c910.png">

**Comment by devowhippit** [comment]
Fixed in the latest release 😄
