### ISSUE TITLE
Mobile Nav: demo not displaying properly

### ISSUE THREAD

**Issue by KISS** [CityOfNewYork/ACCESS-NYC-PATTERNS#10]
Mobile nav demo doesn't display at 960px breakpoint:

<img width="942" alt="screen shot 2018-10-25 at 12 23 15 pm" src="https://user-images.githubusercontent.com/182383/47515399-cd691780-d850-11e8-859e-60367d64d3e5.png">

Up to 960px, demo displays but the code snippet isn't fully in view.
<img width="932" alt="screen shot 2018-10-25 at 12 25 01 pm" src="https://user-images.githubusercontent.com/182383/47515532-20db6580-d851-11e8-8fe4-1ef4ebfc4ec2.png">

**Comment by devowhippit** [comment]
This is part of the behavior of the mobile nav.
