### ISSUE TITLE
File to import not found or unreadable: tailwind.

### ISSUE THREAD

**Issue by theasteve** [CityOfNewYork/ACCESS-NYC-PATTERNS#2]
Integrating the library into Rails breaks at `@import 'tailwind';`  The reason is because Rails asset pipeline doesn't look into `config` folder. Possible solution would be to move `tailwind.js` into `vendor` or `assets.js`?

<img width="1073" alt="screen shot 2018-08-14 at 12 38 21 pm" src="https://user-images.githubusercontent.com/14843767/44105216-fde39504-9fbe-11e8-85fd-b97cb042d334.png">

**Comment by devowhippit** [comment]
I forgot to mention this in the documentation, the tailwind utilities need to be imported differently via this file;

@import 'access-nyc-patterns/dist/styles/_tailwind.scss';
