### ISSUE TITLE
Margin/Padding Under Section Headings for Patterns

### ISSUE THREAD

**Issue by KISS** [CityOfNewYork/ACCESS-NYC-PATTERNS#5]
<img width="926" alt="screen shot 2018-10-24 at 1 50 07 pm" src="https://user-images.githubusercontent.com/182383/47450775-1a3ae880-d794-11e8-8017-92322557f7fc.png">

The separation between the section header (in this case "Buttons") and the first example/demo (in this case "Base Styling") is unclear. Implementing something similar to the section divider on the About page (below) is one option. 

<img width="919" alt="screen shot 2018-10-24 at 1 51 22 pm" src="https://user-images.githubusercontent.com/182383/47450934-7867cb80-d794-11e8-837e-e8d57609188a.png">

**Comment by devowhippit** [comment]
I added some extra spacing to the bottom of the page title.
