### ISSUE TITLE
Update grid/add margin at 960px Breakpoint for alignment

### ISSUE THREAD

**Issue by KISS** [CityOfNewYork/ACCESS-NYC-PATTERNS#6]
Up to 959px the layout has a left and right-margin (as pictured below):
<img width="915" alt="screen shot 2018-10-25 at 9 15 41 am" src="https://user-images.githubusercontent.com/182383/47502972-04caca80-d837-11e8-91bc-8b8532561bcb.png">

At 960px the layout no longer has this margin (as pictured below) and the layout looks broken/messy:
<img width="956" alt="screen shot 2018-10-25 at 9 15 15 am" src="https://user-images.githubusercontent.com/182383/47503176-7b67c800-d837-11e8-8abe-c7953d5f6f4b.png">

**Comment by devowhippit** [comment]
done!
