### ISSUE TITLE
Colors: demo code content

### ISSUE THREAD

**Issue by KISS** [CityOfNewYork/ACCESS-NYC-PATTERNS#7]
<img width="941" alt="screen shot 2018-10-25 at 9 44 27 am" src="https://user-images.githubusercontent.com/182383/47504711-cafbc300-d83a-11e8-9911-ddcef9db94bc.png">

1. If the code snippet is multiline, it looks very crowded. Ideally in this case, it should break into a new line
2. Add more spacing between the code snippet and it's respective title (in most cases this would be fixed by breaking into a new line)

**Comment by devowhippit** [comment]
@KISS do you think the labels (Hex, Border, Text...) are valuable enough to keep? My first thought would be to break them to the next line as well but I would be concerned that would make the cards too tall... so, I was wondering if we can just remove some clutter to for them to work better. That may not be a big deal however. CC @kimpenguin @theasteve

**Comment by KISS** [comment]
@devowhippit tested this and you're right, the cards do become fairly long. This makes the layout look odd if it's not uniform. I suggest keeping the Hex label and removing the other labels (example below) since the naming convention makes the class names self-explanatory. 

<img width="418" alt="screen shot 2018-11-01 at 12 30 24 pm" src="https://user-images.githubusercontent.com/182383/47865194-ef731480-ddd1-11e8-9e8e-4862cc7a3ca0.png">


BTW, just noticed the Hex for Color Transparent is rgba: 
<img width="215" alt="screen shot 2018-11-01 at 12 26 36 pm" src="https://user-images.githubusercontent.com/182383/47865034-8b505080-ddd1-11e8-9c86-8ef875ee1a67.png">

**Comment by kimpenguin** [comment]
@devowhippit @KISS  
I think the labels are worth keeping. Makes it easy to see what the values are referencing (yes, the class is self-explanatory, but might not be that obvious to all users)
What about updating the layout from 4 to 3? With increased padding between the label and code?
I agree that the new line would make the card too tall.

**Comment by devowhippit** [comment]
3 columns it is :)
