### ISSUE TITLE
Tables, Content: demo and code snippet overlap

### ISSUE THREAD

**Issue by KISS** [CityOfNewYork/ACCESS-NYC-PATTERNS#8]
Overlap from 758px - 1098px

<img width="952" alt="screen shot 2018-10-25 at 11 20 27 am" src="https://user-images.githubusercontent.com/182383/47511381-15d00780-d848-11e8-8ea4-7aa174d45900.png">

**Comment by devowhippit** [comment]
I made this view use the "gutter" layout which will stack the demo over the markup. The width of tables is dependent on the content so not much to do about it other than change the layout.
