### ISSUE TITLE
Typography: separate out H1..H5 code snippets for clarity

### ISSUE THREAD

**Issue by KISS** [CityOfNewYork/ACCESS-NYC-PATTERNS#9]
Separating out the H1..H5 tag code snippets or preceding the examples with "Hx" will help clarify which heading belongs to which code snippets at first glance. 

<img width="940" alt="screen shot 2018-10-25 at 11 34 24 am" src="https://user-images.githubusercontent.com/182383/47512342-ffc34680-d849-11e8-92dd-d45a6a112c4a.png">

**Comment by devowhippit** [comment]
Done!
